# Generated by Django 6.0.5 on 2026-05-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. 111, 46, 102', max_length=10)),
                ('destination', models.CharField(max_length=100)),
                ('fare_estimate', models.CharField(help_text='e.g. 50 - 100 KES', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_major_hub', models.BooleanField(default=False, help_text='Is this a main boarding point like Railways?')),
                ('order', models.PositiveIntegerField(default=0, help_text='The sequence of this stop on the route')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='transit.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
