# Generated by Django 6.0.5 on 2026-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0002_contribution_savedroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.AddField(
            model_name='contribution',
            name='name',
            field=models.CharField(blank=True, help_text='Optional — your name or nickname', max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SavedRoute',
        ),
    ]
