# Generated by Django 4.2.7 on 2026-05-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_remove_contribution_user_contribution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='search_tags',
            field=models.TextField(blank=True, default='', help_text='Auto-populated: all stage names for fast searching'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
