# Generated by Django 4.2.7 on 2026-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_route_search_tags_alter_contribution_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='sacco',
            field=models.CharField(blank=True, default='', help_text='e.g. Super Metro, Double M', max_length=100),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_undesignated',
            field=models.BooleanField(default=False, help_text='Informal boarding point (GTFS type U)'),
        ),
        migrations.AddField(
            model_name='stage',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Street name e.g. Kencom, Odeon, Koja', max_length=100),
        ),
    ]
